
paths:
  roi_images_path: "${paths.processed_data}/images_HnE"
  roi_xy_path: "${paths.processed_data}/roi_xy"
  ihc_path: "${paths.processed_data}/images_IHC"
  masks_path: "${paths.processed_data}/masks"
  arrow_right: "${paths.environment_assets}/arrow_right.png"
  arrow_left: "${paths.environment_assets}/arrow_left.png"
  logo: "${paths.environment_assets}/logo.png"
  file_path: ""

colors:
  base_bg: "#ffffff"       # white background base color
  base_fg: "#000000"       # black foreground base color
  activebg: "#9f9c93"      # a gray-ish active background color
  active_bg: "#9f9c93"     # duplicate with underscore, if needed for compatibility
