include: base_config.yaml

paths:
  database_path: "${paths.resources}/final.db"

training_params:
  BACKBONE: ["resnet34", "resnet152"]
  model_type: "resnet152"
  n_classes: 4
  activation: "softmax"
  learning_rate: 0.0001
  batch_size: 3
  img_size: 512
